Apex Assignment1 commit
kumarnitabh/RetriveFromOrgAssn pull request #3
Opened 2024-11-25 07:32 UTC by kumarnitabh

2024-11-25 15:32 UTC, shubhamAgarwal242 requested changes

2024-11-25 15:32 UTC, shubhamAgarwal242 commented on classes/Assignment1.cls
> +public class Assignment1 {
@kumarnitabh, Please update the class name.
Class name should be proper with a meaning

2024-11-25 15:32 UTC, shubhamAgarwal242 commented on classes/Assignment1.cls
> +    public static void Assignment1() {
@kumarnitabh, Please update the method name as well

2024-11-25 15:32 UTC, shubhamAgarwal242 commented on classes/Assignment1Part2.cls
> +
@kumarnitabh, this type of line space is not needed

2024-11-25 15:32 UTC, shubhamAgarwal242 commented on classes/Assignment1Part3.cls
> +        List<Integer> RandomNumbers=new List<Integer>{3,43,12,76,11,32,91,62,72,37};
@kumarnitabh, variable name should be followed up camel case

2024-11-26 11:19 UTC, shubhamAgarwal242 requested changes

2024-11-26 11:19 UTC, shubhamAgarwal242 commented on classes/EmployeeDepartmentMap.cls
> +    public static void employeeData() {
@kumarnitabh, please add the method comments as well

2024-11-26 11:19 UTC, shubhamAgarwal242 commented on classes/EmployeeDepartmentMap.cls
> +        Map<String, List<String>> dataOfEmployee =new Map<String, List<String>>();
@kumarnitabh, Use proper variable name like : mapOfDepartmentToEmployees

2024-11-26 11:19 UTC, shubhamAgarwal242 commented on classes/OperationsOnList.cls
> +        List<Integer> numbersList =new List<Integer>();
@kumarnitabh, As discussed, variable name should be like: listOfNumbers

2024-11-26 11:19 UTC, shubhamAgarwal242 commented on classes/OperationsOnList.cls
> +    public static void sortedList() {
@kumarnitabh, Add method comments

2024-11-26 11:19 UTC, shubhamAgarwal242 commented on classes/OperationsOnSet.cls
> +    public static void setDifferentOperation () {
@kumarnitabh, Please add the method comments

2024-11-26 11:19 UTC, shubhamAgarwal242 commented on classes/OperationsOnSet.cls
> +        Set<String> studentSet1 = new Set<String>();
@kumarnitabh, variable name should be setOfStudents1

2024-11-27 11:07 UTC, kumarnitabh commented on classes/EmployeeDepartmentMap.cls
> +    public static void employeeData() {
Resolved

2024-11-27 11:10 UTC, shubhamAgarwal242 approved these changes

2024-11-27 11:19 UTC, merged